version: '2.0'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 ./PredoxWeb/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
